name: Cross-compile Linux binary

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Add musl target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build release binary for musl
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Upload Linux binary
        uses: actions/upload-artifact@v3
        with:
          name: matheasy-linux-musl
          path: target/x86_64-unknown-linux-musl/release/matheasy
